(declare-const x00 Bool)
(assert (= x00 true))
(declare-const x01 Bool)
(assert (= x01 false))
(declare-const x02 Bool)
(assert (= x02 true))
(declare-const x03 Bool)
(assert (= x03 true))
(declare-const x04 Bool)
(assert (= x04 false))
(declare-const x05 Bool)
(assert (= x05 false))
(declare-const x06 Bool)
(assert (= x06 true))
(declare-const x07 Bool)
(assert (= x07 true))
(declare-const x08 Bool)
(assert (= x08 false))
(declare-const x09 Bool)
(assert (= x09 true))
(declare-const x10 Bool)
(assert (= x10 true))
(declare-const x11 Bool)
(assert (= x11 true))
(declare-const x12 Bool)
(assert (= x12 true))
(declare-const x13 Bool)
(assert (= x13 true))
(declare-const x14 Bool)
(assert (= x14 true))
(declare-const x15 Bool)
(assert (= x15 false))
(declare-const x16 Bool)
(assert (= x16 true))
(declare-const x17 Bool)
(assert (= x17 false))
(declare-const x18 Bool)
(assert (= x18 true))
(declare-const x19 Bool)
(assert (= x19 true))
(declare-const x20 Bool)
(assert (= x20 false))
(declare-const x21 Bool)
(assert (= x21 false))
(declare-const x22 Bool)
(assert (= x22 true))
(declare-const x23 Bool)
(assert (= x23 false))
(declare-const x24 Bool)
(assert (= x24 true))
(declare-const x25 Bool)
(assert (= x25 false))
(declare-const x26 Bool)
(assert (= x26 true))
(declare-const x27 Bool)
(assert (= x27 false))
(declare-const x28 Bool)
(assert (= x28 true))
(declare-const x29 Bool)
(assert (= x29 true))
(declare-const x30 Bool)
(assert (= x30 false))
(declare-const x31 Bool)
(assert (= x31 false))
(declare-const x32 Bool)
(assert (= x32 true))
(declare-const x33 Bool)
(assert (= x33 true))
(declare-const x34 Bool)
(assert (= x34 true))
(declare-const x35 Bool)
(assert (= x35 false))
(declare-const x36 Bool)
(assert (= x36 true))
(declare-const x37 Bool)
(assert (= x37 true))
(declare-const x38 Bool)
(assert (= x38 false))
(declare-const x39 Bool)
(assert (= x39 false))
(declare-const x40 Bool)
(assert (= x40 true))
(declare-const x41 Bool)
(assert (= x41 true))
(declare-const x42 Bool)
(assert (= x42 false))
(declare-const x43 Bool)
(assert (= x43 false))
(declare-const x44 Bool)
(assert (= x44 true))
(declare-const y00 Bool)
(assert (= y00 true))
(declare-const y01 Bool)
(assert (= y01 false))
(declare-const y02 Bool)
(assert (= y02 false))
(declare-const y03 Bool)
(assert (= y03 true))
(declare-const y04 Bool)
(assert (= y04 true))
(declare-const y05 Bool)
(assert (= y05 false))
(declare-const y06 Bool)
(assert (= y06 false))
(declare-const y07 Bool)
(assert (= y07 false))
(declare-const y08 Bool)
(assert (= y08 false))
(declare-const y09 Bool)
(assert (= y09 false))
(declare-const y10 Bool)
(assert (= y10 false))
(declare-const y11 Bool)
(assert (= y11 true))
(declare-const y12 Bool)
(assert (= y12 false))
(declare-const y13 Bool)
(assert (= y13 false))
(declare-const y14 Bool)
(assert (= y14 true))
(declare-const y15 Bool)
(assert (= y15 true))
(declare-const y16 Bool)
(assert (= y16 false))
(declare-const y17 Bool)
(assert (= y17 false))
(declare-const y18 Bool)
(assert (= y18 true))
(declare-const y19 Bool)
(assert (= y19 false))
(declare-const y20 Bool)
(assert (= y20 false))
(declare-const y21 Bool)
(assert (= y21 false))
(declare-const y22 Bool)
(assert (= y22 true))
(declare-const y23 Bool)
(assert (= y23 true))
(declare-const y24 Bool)
(assert (= y24 false))
(declare-const y25 Bool)
(assert (= y25 false))
(declare-const y26 Bool)
(assert (= y26 false))
(declare-const y27 Bool)
(assert (= y27 true))
(declare-const y28 Bool)
(assert (= y28 true))
(declare-const y29 Bool)
(assert (= y29 true))
(declare-const y30 Bool)
(assert (= y30 false))
(declare-const y31 Bool)
(assert (= y31 true))
(declare-const y32 Bool)
(assert (= y32 true))
(declare-const y33 Bool)
(assert (= y33 false))
(declare-const y34 Bool)
(assert (= y34 true))
(declare-const y35 Bool)
(assert (= y35 true))
(declare-const y36 Bool)
(assert (= y36 false))
(declare-const y37 Bool)
(assert (= y37 false))
(declare-const y38 Bool)
(assert (= y38 true))
(declare-const y39 Bool)
(assert (= y39 true))
(declare-const y40 Bool)
(assert (= y40 true))
(declare-const y41 Bool)
(assert (= y41 false))
(declare-const y42 Bool)
(assert (= y42 false))
(declare-const y43 Bool)
(assert (= y43 true))
(declare-const y44 Bool)
(assert (= y44 true))

(declare-const njs Bool)
(declare-const pvb Bool)
(declare-const fjh Bool)
(assert (= (and njs pvb) fjh))
(declare-const dcm Bool)
(assert (= (and y12 x12) dcm))
(declare-const srv Bool)
(declare-const dfc Bool)
(declare-const z22 Bool)
(assert (= (xor srv dfc) z22))
(declare-const qwb Bool)
(declare-const vmp Bool)
(declare-const z14 Bool)
(assert (= (xor qwb vmp) z14))
(declare-const z10 Bool)
(assert (= (xor njs pvb) z10))
(declare-const cjn Bool)
(declare-const dfj Bool)
(declare-const fgc Bool)
(assert (= (or cjn dfj) fgc))
(declare-const kpp Bool)
(declare-const tvh Bool)
(declare-const z34 Bool)
(assert (= (xor kpp tvh) z34))
(declare-const tbq Bool)
(declare-const rdf Bool)
(declare-const frv Bool)
(assert (= (or tbq rdf) frv))
(declare-const drs Bool)
(assert (= (and y40 x40) drs))
(declare-const pqh Bool)
(declare-const mmh Bool)
(declare-const z05 Bool)
(assert (= (xor pqh mmh) z05))
(declare-const jkt Bool)
(assert (= (xor x26 y26) jkt))
(declare-const qqp Bool)
(declare-const dmw Bool)
(declare-const kqp Bool)
(assert (= (and qqp dmw) kqp))
(declare-const qsh Bool)
(declare-const wfw Bool)
(declare-const qcr Bool)
(assert (= (or qsh wfw) qcr))
(declare-const hvw Bool)
(declare-const qnn Bool)
(declare-const vgk Bool)
(assert (= (and hvw qnn) vgk))
(declare-const bkc Bool)
(declare-const wsq Bool)
(declare-const ckv Bool)
(assert (= (or bkc wsq) ckv))
(declare-const bbh Bool)
(declare-const z03 Bool)
(assert (= (xor ckv bbh) z03))
(declare-const frj Bool)
(declare-const hqq Bool)
(declare-const z02 Bool)
(assert (= (xor frj hqq) z02))
(declare-const qff Bool)
(declare-const stw Bool)
(declare-const wsv Bool)
(assert (= (or qff stw) wsv))
(declare-const qpq Bool)
(declare-const vnr Bool)
(declare-const z30 Bool)
(assert (= (xor qpq vnr) z30))
(declare-const pbk Bool)
(declare-const kqc Bool)
(declare-const z15 Bool)
(assert (= (xor pbk kqc) z15))
(declare-const mvp Bool)
(declare-const pbv Bool)
(declare-const dbj Bool)
(assert (= (or mvp pbv) dbj))
(assert (= (and x15 y15) qsh))
(declare-const wcs Bool)
(declare-const cqk Bool)
(assert (= (or wcs cqk) kpp))
(declare-const bmr Bool)
(declare-const z32 Bool)
(assert (= (xor bmr fgc) z32))
(declare-const qjf Bool)
(assert (= (xor y42 x42) qjf))
(declare-const rng Bool)
(assert (= (and srv dfc) rng))
(declare-const rsq Bool)
(declare-const nts Bool)
(declare-const brq Bool)
(assert (= (and rsq nts) brq))
(declare-const fhv Bool)
(declare-const hjw Bool)
(declare-const wwg Bool)
(assert (= (and fhv hjw) wwg))
(declare-const phw Bool)
(assert (= (and x06 y06) phw))
(declare-const vtf Bool)
(declare-const gdw Bool)
(declare-const kpc Bool)
(assert (= (and vtf gdw) kpc))
(declare-const wvv Bool)
(declare-const wbf Bool)
(declare-const qdh Bool)
(assert (= (and wvv wbf) qdh))
(declare-const nhs Bool)
(assert (= (and y28 x28) nhs))
(declare-const ttv Bool)
(assert (= (and y04 x04) ttv))
(declare-const cts Bool)
(declare-const bcd Bool)
(assert (= (xor cts bcd) qqp))
(declare-const rkt Bool)
(assert (= (and mmh pqh) rkt))
(declare-const z37 Bool)
(assert (= (xor hjw fhv) z37))
(declare-const jdd Bool)
(declare-const rbm Bool)
(declare-const z36 Bool)
(assert (= (and jdd rbm) z36))
(declare-const drt Bool)
(declare-const tpt Bool)
(declare-const z31 Bool)
(assert (= (xor drt tpt) z31))
(declare-const gcf Bool)
(assert (= (xor y20 x20) gcf))
(declare-const ptf Bool)
(assert (= (and x27 y27) ptf))
(declare-const z41 Bool)
(assert (= (xor qnn hvw) z41))
(declare-const msq Bool)
(assert (= (and x13 y13) msq))
(declare-const cbr Bool)
(declare-const hjd Bool)
(declare-const z07 Bool)
(assert (= (xor cbr hjd) z07))
(declare-const mkv Bool)
(declare-const hgp Bool)
(declare-const z45 Bool)
(assert (= (or mkv hgp) z45))
(declare-const spp Bool)
(assert (= (xor y35 x35) spp))
(declare-const nrk Bool)
(assert (= (xor x08 y08) nrk))
(assert (= (xor y03 x03) bbh))
(declare-const fhc Bool)
(declare-const ggh Bool)
(declare-const fwt Bool)
(assert (= (or fhc ggh) fwt))
(declare-const whj Bool)
(declare-const vrh Bool)
(declare-const qpj Bool)
(assert (= (and whj vrh) qpj))
(assert (= (xor x34 y34) tvh))
(declare-const mpm Bool)
(assert (= (and y43 x43) mpm))
(assert (= (xor y15 x15) pbk))
(assert (= (xor x23 y23) bcd))
(declare-const bwv Bool)
(declare-const tcd Bool)
(declare-const sgv Bool)
(assert (= (and bwv tcd) sgv))
(declare-const jcd Bool)
(assert (= (and bcd cts) jcd))
(declare-const ggs Bool)
(declare-const qmw Bool)
(assert (= (or ggs qmw) tpt))
(declare-const gdm Bool)
(declare-const jkm Bool)
(declare-const z09 Bool)
(assert (= (xor gdm jkm) z09))
(declare-const pgm Bool)
(assert (= (xor y38 x38) pgm))
(declare-const vmc Bool)
(assert (= (and x19 y19) vmc))
(declare-const dtc Bool)
(declare-const ggg Bool)
(assert (= (or dtc ggg) kqc))
(assert (= (and hqq frj) bkc))
(declare-const smv Bool)
(declare-const bhh Bool)
(assert (= (or smv wwg) bhh))
(declare-const tfq Bool)
(assert (= (and y17 x17) tfq))
(assert (= (and x14 y14) dtc))
(assert (= (and y39 x39) ggh))
(declare-const jmh Bool)
(declare-const cjc Bool)
(declare-const gfp Bool)
(assert (= (and jmh cjc) gfp))
(declare-const mgj Bool)
(declare-const z12 Bool)
(assert (= (xor mgj wsv) z12))
(declare-const ftd Bool)
(declare-const wcw Bool)
(declare-const hjm Bool)
(assert (= (and ftd wcw) hjm))
(assert (= (xor y19 x19) whj))
(declare-const ksd Bool)
(declare-const vwf Bool)
(assert (= (and nrk ksd) vwf))
(declare-const fgq Bool)
(declare-const drp Bool)
(assert (= (and fgq spp) drp))
(declare-const z18 Bool)
(assert (= (xor rsq nts) z18))
(assert (= (xor y10 x10) njs))
(declare-const qdb Bool)
(declare-const z04 Bool)
(assert (= (xor frv qdb) z04))
(declare-const wbk Bool)
(declare-const fcv Bool)
(assert (= (or wbk fcv) fgq))
(declare-const z19 Bool)
(assert (= (xor whj vrh) z19))
(assert (= (and tvh kpp) wbk))
(declare-const pwt Bool)
(assert (= (xor y39 x39) pwt))
(declare-const scg Bool)
(declare-const gkj Bool)
(declare-const grv Bool)
(assert (= (or scg gkj) grv))
(declare-const dfn Bool)
(assert (= (xor dfn qcr) pbv))
(assert (= (xor x27 y27) ftd))
(declare-const svg Bool)
(assert (= (or svg tfq) rsq))
(declare-const fkd Bool)
(declare-const z40 Bool)
(assert (= (xor fkd fwt) z40))
(declare-const pdq Bool)
(assert (= (and x07 y07) pdq))
(declare-const hnt Bool)
(assert (= (xor y13 x13) hnt))
(declare-const vpm Bool)
(declare-const z21 Bool)
(assert (= (xor grv vpm) z21))
(assert (= (xor y02 x02) frj))
(declare-const dbp Bool)
(declare-const z26 Bool)
(assert (= (xor jkt dbp) z26))
(declare-const wdr Bool)
(declare-const z23 Bool)
(assert (= (or wdr jcd) z23))
(declare-const wns Bool)
(assert (= (and x21 y21) wns))
(declare-const btn Bool)
(assert (= (and y08 x08) btn))
(declare-const z24 Bool)
(assert (= (xor qqp dmw) z24))
(declare-const wqt Bool)
(assert (= (and x01 y01) wqt))
(declare-const frw Bool)
(declare-const hdp Bool)
(declare-const hgq Bool)
(assert (= (and frw hdp) hgq))
(declare-const frk Bool)
(declare-const wpk Bool)
(assert (= (and frk wpk) hgp))
(assert (= (xor x07 y07) cbr))
(declare-const jgm Bool)
(assert (= (and x29 y29) jgm))
(assert (= (or sgv wqt) hqq))
(assert (= (and tpt drt) dfj))
(declare-const sdn Bool)
(declare-const kqk Bool)
(assert (= (or sdn rkt) kqk))
(declare-const vjj Bool)
(assert (= (and frv qdb) vjj))
(declare-const thp Bool)
(declare-const ncw Bool)
(assert (= (or fjh thp) ncw))
(declare-const vvr Bool)
(assert (= (and y26 x26) vvr))
(declare-const kcs Bool)
(assert (= (and x25 y25) kcs))
(declare-const z27 Bool)
(assert (= (xor ftd wcw) z27))
(declare-const z01 Bool)
(assert (= (xor tcd bwv) z01))
(declare-const brk Bool)
(declare-const z06 Bool)
(assert (= (xor brk kqk) z06))
(assert (= (and x10 y10) thp))
(declare-const z25 Bool)
(assert (= (xor frw hdp) z25))
(declare-const hsh Bool)
(assert (= (and pgm bhh) hsh))
(assert (= (xor x24 y24) dmw))
(declare-const bkv Bool)
(assert (= (or vmc qpj) bkv))
(assert (= (and x44 y44) mkv))
(declare-const knh Bool)
(declare-const rps Bool)
(assert (= (or knh vgk) rps))
(assert (= (and dfn qcr) mvp))
(declare-const tqj Bool)
(assert (= (or tqj rng) cts))
(declare-const tbb Bool)
(assert (= (or tbb wns) srv))
(declare-const pjj Bool)
(assert (= (or msq pjj) vmp))
(declare-const ghn Bool)
(assert (= (or drs ghn) hvw))
(declare-const rrb Bool)
(declare-const rms Bool)
(assert (= (or hsh rrb) rms))
(declare-const bgt Bool)
(declare-const z17 Bool)
(assert (= (xor dbj bgt) z17))
(assert (= (or mpm kpc) frk))
(assert (= (and bgt dbj) svg))
(assert (= (xor x40 y40) fkd))
(declare-const z16 Bool)
(assert (= (and x16 y16) z16))
(declare-const dvs Bool)
(assert (= (and cbr hjd) dvs))
(declare-const fsb Bool)
(declare-const drv Bool)
(assert (= (or fsb drv) gdw))
(declare-const z29 Bool)
(assert (= (xor cjc jmh) z29))
(assert (= (or pdq dvs) ksd))
(declare-const rpw Bool)
(declare-const fbq Bool)
(assert (= (or rpw fbq) fhv))
(assert (= (xor y05 x05) pqh))
(assert (= (and x30 y30) ggs))
(declare-const bmb Bool)
(assert (= (or bmb drp) jdd))
(declare-const fbm Bool)
(declare-const z13 Bool)
(assert (= (xor hnt fbm) z13))
(assert (= (and y42 x42) fsb))
(assert (= (and qpq vnr) qmw))
(assert (= (xor x11 y11) qff))
(assert (= (and gcf bkv) gkj))
(declare-const z28 Bool)
(assert (= (xor wvv wbf) z28))
(assert (= (and x05 y05) sdn))
(declare-const pqp Bool)
(assert (= (or pqp phw) hjd))
(assert (= (xor jdd rbm) fbq))
(declare-const njt Bool)
(assert (= (or njt kqp) frw))
(declare-const z00 Bool)
(assert (= (xor y00 x00) z00))
(assert (= (and y31 x31) cjn))
(assert (= (xor x32 y32) bmr))
(assert (= (and x34 y34) fcv))
(assert (= (and y24 x24) njt))
(assert (= (xor y06 x06) brk))
(assert (= (xor x12 y12) mgj))
(assert (= (and ckv bbh) tbq))
(declare-const z42 Bool)
(assert (= (xor rps qjf) z42))
(assert (= (and x33 y33) cqk))
(declare-const nhk Bool)
(assert (= (and y09 x09) nhk))
(declare-const mbp Bool)
(assert (= (xor y33 x33) mbp))
(assert (= (xor x04 y04) qdb))
(assert (= (and x22 y22) tqj))
(assert (= (and y20 x20) scg))
(assert (= (xor y01 x01) tcd))
(declare-const shp Bool)
(assert (= (and fgc bmr) shp))
(declare-const pnw Bool)
(declare-const z33 Bool)
(assert (= (xor mbp pnw) z33))
(declare-const z44 Bool)
(assert (= (xor frk wpk) z44))
(assert (= (xor y43 x43) vtf))
(assert (= (xor x37 y37) hjw))
(assert (= (and y03 x03) rdf))
(declare-const z39 Bool)
(assert (= (xor rms pwt) z39))
(declare-const z38 Bool)
(assert (= (xor bhh pgm) z38))
(declare-const z35 Bool)
(assert (= (xor spp fgq) z35))
(assert (= (xor y22 x22) dfc))
(assert (= (and qjf rps) drv))
(assert (= (or kcs hgq) dbp))
(assert (= (xor y29 x29) cjc))
(assert (= (xor x25 y25) hdp))
(declare-const hbq Bool)
(assert (= (or hbq dcm) fbm))
(assert (= (and brk kqk) pqp))
(assert (= (and qwb vmp) ggg))
(declare-const gpb Bool)
(assert (= (or gpb shp) pnw))
(assert (= (and y02 x02) wsq))
(assert (= (or ptf hjm) wvv))
(assert (= (xor x18 y18) nts))
(assert (= (and x23 y23) wdr))
(assert (= (xor x09 y09) jkm))
(assert (= (and x36 y36) rpw))
(assert (= (and x32 y32) gpb))
(assert (= (and mbp pnw) wcs))
(assert (= (or jgm gfp) qpq))
(declare-const qnw Bool)
(assert (= (and x11 y11) qnw))
(declare-const z20 Bool)
(assert (= (xor bkv gcf) z20))
(declare-const ftf Bool)
(assert (= (or nhk ftf) pvb))
(declare-const z43 Bool)
(assert (= (xor gdw vtf) z43))
(assert (= (or vjj ttv) mmh))
(assert (= (and x41 y41) knh))
(declare-const z11 Bool)
(assert (= (xor ncw qnw) z11))
(assert (= (xor y28 x28) wbf))
(assert (= (xor y36 x36) rbm))
(assert (= (and mgj wsv) hbq))
(assert (= (and hnt fbm) pjj))
(declare-const bfd Bool)
(assert (= (or brq bfd) vrh))
(assert (= (xor x17 y17) bgt))
(declare-const z08 Bool)
(assert (= (xor ksd nrk) z08))
(assert (= (and x38 y38) rrb))
(assert (= (and fwt fkd) ghn))
(assert (= (and ncw qnw) stw))
(assert (= (and x18 y18) bfd))
(assert (= (and y00 x00) bwv))
(assert (= (and gdm jkm) ftf))
(assert (= (and rms pwt) fhc))
(assert (= (xor x16 y16) dfn))
(assert (= (and y37 x37) smv))
(assert (= (and x35 y35) bmb))
(assert (= (xor y30 x30) vnr))
(declare-const dbt Bool)
(assert (= (and jkt dbp) dbt))
(assert (= (xor y41 x41) qnn))
(assert (= (xor x31 y31) drt))
(assert (= (or qdh nhs) jmh))
(assert (= (or vwf btn) gdm))
(assert (= (xor y44 x44) wpk))
(assert (= (xor x14 y14) qwb))
(assert (= (xor x21 y21) vpm))
(assert (= (and pbk kqc) wfw))
(assert (= (or vvr dbt) wcw))
(assert (= (and grv vpm) tbb))
(check-sat)
(get-value (z45 z44 z43 z42 z41 z40 z39 z38 z37 z36 z35 z34 z33 z32 z31 z30 z29 z28 z27 z26 z25 z24 z23 z22 z21 z20 z19 z18 z17 z16 z15 z14 z13 z12 z11 z10 z09 z08 z07 z06 z05 z04 z03 z02 z01 z00 ))